version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mingling-db
    environment:
      MYSQL_ROOT_PASSWORD: Mingle123!
      MYSQL_DATABASE: mingling
      TZ: Asia/Seoul
    ports: ["3307:3306"]
    volumes: ["dbdata:/var/lib/mysql"]
volumes:
  dbdata: 